// PLang Code Generator — transpiles AST to JavaScript

import * as AST from "./ast";

export class CodeGenerator {
  private indent: number = 0;
  private output: string[] = [];
  private testNames: string[] = [];

  generate(program: AST.Program): string {
    this.output = [];
    this.testNames = [];

    // Header
    this.emit("// Generated by PLang compiler");
    this.emit(`// Module: ${program.module.path.join(".")}`);
    this.emit('"use strict";');
    this.emit("");

    // Runtime helpers
    this.emitRuntime();

    // Imports (mapped to requires)
    for (const imp of program.imports) {
      this.emitImport(imp);
    }

    if (program.imports.length > 0) this.emit("");

    // Declarations
    for (const decl of program.declarations) {
      this.emitDecl(decl);
      this.emit("");
    }

    // Auto-run main if it exists
    const hasMain = program.declarations.some(
      d => d.kind === "FnDecl" && d.name === "main"
    );
    if (hasMain) {
      this.emit("// Entry point");
      this.emit("if (require.main === module) {");
      this.indent++;
      this.emit("const __result = main();");
      this.emit("if (__result instanceof Promise) __result.catch(e => { console.error(e); process.exit(1); });");
      this.indent--;
      this.emit("}");
    }

    return this.output.join("\n");
  }

  generateTestRunner(program: AST.Program): string {
    const code = this.generate(program);

    if (this.testNames.length === 0) return code;

    const runner: string[] = [code, "", "// Test runner"];
    runner.push("(async () => {");
    runner.push("  let __passed = 0, __failed = 0;");
    for (const name of this.testNames) {
      const fnName = this.testFnName(name);
      runner.push(`  try { await ${fnName}(); __passed++; console.log("  PASS: ${this.escapeStr(name)}"); }`);
      runner.push(`  catch (e) { __failed++; console.error("  FAIL: ${this.escapeStr(name)}", e.message); }`);
    }
    runner.push('  console.log(`\\n${__passed} passed, ${__failed} failed`);');
    runner.push("  if (__failed > 0) process.exit(1);");
    runner.push("})();");

    return runner.join("\n");
  }

  private emitRuntime(): void {
    this.emit("// PLang runtime");
    this.emit("class __PLangError extends Error {");
    this.emit("  constructor(tag, data) { super(tag); this.tag = tag; this.data = data; }");
    this.emit("}");
    this.emit("");
    this.emit("function __ok(value) { return { __tag: 'Ok', value }; }");
    this.emit("function __err(error) { return { __tag: 'Err', error }; }");
    this.emit("function __some(value) { return { __tag: 'Some', value }; }");
    this.emit("const __none = { __tag: 'None' };");
    this.emit("");
    this.emit("function __propagate(result) {");
    this.emit("  if (result && result.__tag === 'Err') throw new __PLangError('propagate', result.error);");
    this.emit("  if (result && result.__tag === 'Ok') return result.value;");
    this.emit("  return result;");
    this.emit("}");
    this.emit("");
    this.emit("function __range(start, end) {");
    this.emit("  const arr = [];");
    this.emit("  for (let i = start; i < end; i++) arr.push(i);");
    this.emit("  return arr;");
    this.emit("}");
    this.emit("");
    this.emit("function __approxEq(a, b) { return Math.abs(a - b) < 1e-9; }");
    this.emit("");
    this.emit("function __assert(condition, message) {");
    this.emit('  if (!condition) throw new Error("Assertion failed: " + (message || ""));');
    this.emit("}");
    this.emit("");
    this.emit("function __require(condition) {");
    this.emit('  if (!condition) throw new Error("Precondition failed");');
    this.emit("}");
    this.emit("");
    // String concat
    this.emit("function __concat(a, b) { return String(a) + String(b); }");
    this.emit("");
    // Standard library stubs
    this.emit("const std = {");
    this.emit("  io: {");
    this.emit("    println: (s) => { console.log(s); return __ok(undefined); },");
    this.emit("    readln: () => __ok(''),");
    this.emit("  },");
    this.emit("  math: {");
    this.emit("    pi: Math.PI,");
    this.emit("    sqrt: Math.sqrt,");
    this.emit("    abs: Math.abs,");
    this.emit("    floor: Math.floor,");
    this.emit("    ceil: Math.ceil,");
    this.emit("    round: Math.round,");
    this.emit("  },");
    this.emit("};");
    this.emit("");
    // Global convenience
    this.emit("const println = std.io.println;");
    this.emit("const math = std.math;");
    this.emit("");
  }

  private emitImport(imp: AST.ImportDecl): void {
    // Imports are handled by the runtime stubs for now
    this.emit(`// import: ${imp.path.join(".")}`);
  }

  private emitDecl(decl: AST.TopLevelDecl): void {
    switch (decl.kind) {
      case "FnDecl": this.emitFnDecl(decl); break;
      case "TypeDecl": this.emitTypeDecl(decl); break;
      case "TraitDecl": this.emitTraitDecl(decl); break;
      case "ImplDecl": this.emitImplDecl(decl); break;
      case "LetDecl": this.emitLetDecl(decl); break;
      case "TestDecl": this.emitTestDecl(decl); break;
    }
  }

  private emitFnDecl(decl: AST.FnDecl): void {
    const asyncPrefix = decl.isAsync ? "async " : "";
    const params = decl.params.map(p => p.name).join(", ");
    const exportPrefix = decl.isPublic ? "module.exports." : "";

    if (decl.isPublic) {
      this.emit(`${asyncPrefix}function ${decl.name}(${params}) {`);
      this.indent++;
      this.emitBlockBody(decl.body);
      this.indent--;
      this.emit("}");
      this.emit(`module.exports.${decl.name} = ${decl.name};`);
    } else {
      this.emit(`${asyncPrefix}function ${decl.name}(${params}) {`);
      this.indent++;
      this.emitBlockBody(decl.body);
      this.indent--;
      this.emit("}");
    }
  }

  private emitTypeDecl(decl: AST.TypeDecl): void {
    switch (decl.body.kind) {
      case "RecordTypeBody": {
        // Generate a factory function
        const fields = decl.body.fields.map(f => f.name);
        this.emit(`function ${decl.name}({${fields.join(", ")}}) {`);
        this.emit(`  return { __type: "${decl.name}", ${fields.join(", ")} };`);
        this.emit("}");
        break;
      }
      case "SumTypeBody": {
        // Generate factory functions for each variant
        for (const variant of decl.body.variants) {
          const fields = variant.fields.map(f => f.name);
          if (fields.length > 0) {
            this.emit(`function ${variant.name}({${fields.join(", ")}}) {`);
            this.emit(`  return { __tag: "${variant.name}", __type: "${decl.name}", ${fields.join(", ")} };`);
            this.emit("}");
          } else {
            this.emit(`const ${variant.name} = { __tag: "${variant.name}", __type: "${decl.name}" };`);
          }
        }
        break;
      }
      case "AliasTypeBody":
        this.emit(`// type alias: ${decl.name}`);
        break;
    }
  }

  private emitTraitDecl(decl: AST.TraitDecl): void {
    this.emit(`// trait: ${decl.name}`);
  }

  private emitImplDecl(decl: AST.ImplDecl): void {
    this.emit(`// impl ${decl.traitPath.join(".")} for ${this.typeExprToString(decl.targetType)}`);
    for (const method of decl.methods) {
      const params = method.params
        .filter(p => p.name !== "self")
        .map(p => p.name)
        .join(", ");
      const hasSelf = method.params.some(p => p.name === "self");

      if (hasSelf) {
        // Instance method — add to prototype or as standalone
        this.emit(`function ${decl.traitPath.join("_")}_${method.name}(__self${params ? ", " + params : ""}) {`);
      } else {
        this.emit(`function ${decl.traitPath.join("_")}_${method.name}(${params}) {`);
      }
      this.indent++;
      this.emitBlockBody(method.body);
      this.indent--;
      this.emit("}");
    }
  }

  private emitLetDecl(decl: AST.LetDecl): void {
    this.emit(`const ${decl.name} = ${this.exprToJs(decl.value)};`);
  }

  private emitTestDecl(decl: AST.TestDecl): void {
    const fnName = this.testFnName(decl.name);
    this.testNames.push(decl.name);
    this.emit(`async function ${fnName}() {`);
    this.indent++;
    this.emitBlockBody(decl.body);
    this.indent--;
    this.emit("}");
  }

  // === Expression → JS ===

  private exprToJs(expr: AST.Expr): string {
    switch (expr.kind) {
      case "IntLiteral": return String(expr.value);
      case "FloatLiteral": return String(expr.value);
      case "StrLiteral": return JSON.stringify(expr.value);
      case "CharLiteral": return JSON.stringify(expr.value);
      case "BoolLiteral": return String(expr.value);
      case "Identifier": return expr.name;

      case "BinaryExpr": {
        const left = this.exprToJs(expr.left);
        const right = this.exprToJs(expr.right);
        if (expr.operator === "++") return `__concat(${left}, ${right})`;
        if (expr.operator === "~=") return `__approxEq(${left}, ${right})`;
        return `(${left} ${expr.operator} ${right})`;
      }

      case "UnaryExpr":
        return `${expr.operator}${this.exprToJs(expr.operand)}`;

      case "CallExpr": {
        const callee = this.exprToJs(expr.callee);
        const args = expr.args.map(a => this.exprToJs(a)).join(", ");
        return `${callee}(${args})`;
      }

      case "MemberExpr":
        return `${this.exprToJs(expr.object)}.${expr.member}`;

      case "PropagateExpr":
        return `__propagate(${this.exprToJs(expr.expr)})`;

      case "IfExpr": {
        const cond = this.exprToJs(expr.condition);
        const then = this.blockToJsExpr(expr.then);
        if (expr.else_) {
          const els = expr.else_.kind === "IfExpr"
            ? this.exprToJs(expr.else_)
            : this.blockToJsExpr(expr.else_);
          return `(${cond} ? ${then} : ${els})`;
        }
        return `(${cond} ? ${then} : undefined)`;
      }

      case "MatchExpr":
        return this.matchToJs(expr);

      case "ForExpr": {
        const iterable = this.exprToJs(expr.iterable);
        return `${iterable}.map((${expr.variable}) => ${this.blockToJsExpr(expr.body)})`;
      }

      case "WhileExpr":
        // While as expression returns void — wrap in IIFE
        return `(() => { while (${this.exprToJs(expr.condition)}) ${this.blockToJsInline(expr.body)} })()`;

      case "BlockExpr":
        return this.blockToJsExpr(expr);

      case "LambdaExpr": {
        const params = expr.params.map(p => p.name).join(", ");
        return `(${params}) => ${this.blockToJsExpr(expr.body)}`;
      }

      case "ListExpr":
        return `[${expr.elements.map(e => this.exprToJs(e)).join(", ")}]`;

      case "RecordExpr": {
        const fields = expr.fields.map(f => {
          if (f.value.kind === "Identifier" && f.value.name === f.name) {
            return f.name; // shorthand
          }
          return `${f.name}: ${this.exprToJs(f.value)}`;
        });
        return `${expr.typeName}({${fields.join(", ")}})`;
      }

      case "RecordUpdateExpr": {
        const base = this.exprToJs(expr.base);
        const updates = expr.updates.map(f => `${f.name}: ${this.exprToJs(f.value)}`).join(", ");
        return `{...${base}, ${updates}}`;
      }

      case "PipeExpr": {
        const callee = this.exprToJs(expr.right.callee);
        const args = [this.exprToJs(expr.left), ...expr.right.args.map(a => this.exprToJs(a))].join(", ");
        return `${callee}(${args})`;
      }

      case "ReturnExpr":
        return expr.value ? `return ${this.exprToJs(expr.value)}` : "return";

      case "BreakExpr": return "break";
      case "ContinueExpr": return "continue";

      case "AwaitExpr":
        return `await ${this.exprToJs(expr.expr)}`;

      case "TaskGroupExpr":
        return `await Promise.all((() => { const __tasks = []; const ${expr.paramName} = { spawn: (fn) => __tasks.push(fn()) }; ${this.blockToJsInline(expr.body)}; return __tasks; })())`;

      case "AssertExpr":
        return `__assert(${this.exprToJs(expr.condition)}, ${JSON.stringify(this.exprToSourceString(expr.condition))})`;

      case "RangeExpr":
        return `__range(${this.exprToJs(expr.start)}, ${this.exprToJs(expr.end)})`;

      default:
        return `/* unsupported: ${(expr as any).kind} */`;
    }
  }

  private matchToJs(expr: AST.MatchExpr): string {
    const subject = this.exprToJs(expr.subject);
    const tempVar = `__match_${Math.floor(Math.random() * 10000)}`;

    const arms = expr.arms.map(arm => {
      const { condition, bindings } = this.patternToCondition(arm.pattern, tempVar);
      const body = this.exprToJs(arm.body);
      const bindingCode = bindings.length > 0
        ? bindings.map(b => `const ${b.name} = ${b.expr};`).join(" ") + " "
        : "";
      return `${condition} ? (() => { ${bindingCode}return ${body}; })()`;
    });

    return `((${tempVar}) => ${arms.join(" : ")} : undefined)(${subject})`;
  }

  private patternToCondition(
    pattern: AST.Pattern,
    subject: string,
  ): { condition: string; bindings: { name: string; expr: string }[] } {
    switch (pattern.kind) {
      case "WildcardPattern":
        return { condition: "true", bindings: [] };

      case "IdentifierPattern":
        return { condition: "true", bindings: [{ name: pattern.name, expr: subject }] };

      case "LiteralPattern": {
        const value = this.exprToJs(pattern.value);
        return { condition: `${subject} === ${value}`, bindings: [] };
      }

      case "VariantPattern": {
        const bindings: { name: string; expr: string }[] = [];
        for (const field of pattern.fields) {
          if (!field.isRest) {
            bindings.push({ name: field.name, expr: `${subject}.${field.name}` });
          }
        }
        return {
          condition: `${subject}.__tag === "${pattern.name}"`,
          bindings,
        };
      }

      case "ListPattern": {
        const conditions: string[] = [];
        const bindings: { name: string; expr: string }[] = [];
        if (!pattern.hasRest) {
          conditions.push(`${subject}.length === ${pattern.elements.length}`);
        } else {
          conditions.push(`${subject}.length >= ${pattern.elements.length}`);
        }
        for (let i = 0; i < pattern.elements.length; i++) {
          const sub = this.patternToCondition(pattern.elements[i], `${subject}[${i}]`);
          if (sub.condition !== "true") conditions.push(sub.condition);
          bindings.push(...sub.bindings);
        }
        return { condition: conditions.join(" && ") || "true", bindings };
      }
    }
  }

  // === Block emission ===

  private emitBlockBody(block: AST.BlockExpr): void {
    for (const stmt of block.statements) {
      this.emitStatement(stmt);
    }
    if (block.finalExpr) {
      this.emit(`return ${this.exprToJs(block.finalExpr)};`);
    }
  }

  private emitStatement(stmt: AST.Statement): void {
    switch (stmt.kind) {
      case "LetDecl":
        this.emit(`const ${stmt.name} = ${this.exprToJs(stmt.value)};`);
        break;
      case "VarDecl":
        this.emit(`let ${stmt.name} = ${this.exprToJs(stmt.value)};`);
        break;
      case "AssignStmt":
        this.emit(`${stmt.target} ${stmt.operator} ${this.exprToJs(stmt.value)};`);
        break;
      case "ExprStmt":
        this.emit(`${this.exprToJs(stmt.expr)};`);
        break;
      case "RequireStmt":
        this.emit(`__require(${this.exprToJs(stmt.condition)});`);
        break;
      case "EnsureStmt":
        // Postconditions are checked after the function body — emitted as a wrapper
        this.emit(`// ensure: |${stmt.paramName}| ${this.exprToSourceString(stmt.condition)}`);
        break;
    }
  }

  private blockToJsExpr(block: AST.BlockExpr): string {
    if (block.statements.length === 0 && block.finalExpr) {
      return this.exprToJs(block.finalExpr);
    }

    const parts: string[] = [];
    for (const stmt of block.statements) {
      parts.push(this.stmtToJs(stmt));
    }
    if (block.finalExpr) {
      parts.push(`return ${this.exprToJs(block.finalExpr)};`);
    }
    return `(() => { ${parts.join(" ")} })()`;
  }

  private blockToJsInline(block: AST.BlockExpr): string {
    const parts: string[] = [];
    for (const stmt of block.statements) {
      parts.push(this.stmtToJs(stmt));
    }
    if (block.finalExpr) {
      parts.push(this.exprToJs(block.finalExpr) + ";");
    }
    return `{ ${parts.join(" ")} }`;
  }

  private stmtToJs(stmt: AST.Statement): string {
    switch (stmt.kind) {
      case "LetDecl": return `const ${stmt.name} = ${this.exprToJs(stmt.value)};`;
      case "VarDecl": return `let ${stmt.name} = ${this.exprToJs(stmt.value)};`;
      case "AssignStmt": return `${stmt.target} ${stmt.operator} ${this.exprToJs(stmt.value)};`;
      case "ExprStmt": return `${this.exprToJs(stmt.expr)};`;
      case "RequireStmt": return `__require(${this.exprToJs(stmt.condition)});`;
      case "EnsureStmt": return `/* ensure */`;
    }
  }

  // === Helpers ===

  private emit(line: string): void {
    const indentation = "  ".repeat(this.indent);
    this.output.push(indentation + line);
  }

  private testFnName(name: string): string {
    return "__test_" + name.replace(/[^a-zA-Z0-9]/g, "_");
  }

  private typeExprToString(type: AST.TypeExpr): string {
    switch (type.kind) {
      case "NamedType": return type.name + (type.typeArgs.length > 0 ? `<${type.typeArgs.map(t => this.typeExprToString(t)).join(", ")}>` : "");
      case "FunctionType": return `(${type.params.map(p => this.typeExprToString(p)).join(", ")}) -> ${this.typeExprToString(type.returnType)}`;
      case "TupleType": return `(${type.elements.map(e => this.typeExprToString(e)).join(", ")})`;
      case "RecordType": return `{ ${type.fields.map(f => `${f.name}: ${this.typeExprToString(f.type)}`).join(", ")} }`;
    }
  }

  private exprToSourceString(expr: AST.Expr): string {
    // Approximate source reconstruction for error messages
    switch (expr.kind) {
      case "BinaryExpr": return `${this.exprToSourceString(expr.left)} ${expr.operator} ${this.exprToSourceString(expr.right)}`;
      case "Identifier": return expr.name;
      case "IntLiteral": return String(expr.value);
      case "CallExpr": return `${this.exprToSourceString(expr.callee)}(...)`;
      default: return "<expr>";
    }
  }

  private escapeStr(s: string): string {
    return s.replace(/"/g, '\\"');
  }
}
