// PLang Code Generator — transpiles AST to JavaScript

import * as AST from "./ast";

export class CodeGenerator {
  private indent: number = 0;
  private output: string[] = [];
  private testNames: string[] = [];
  private mutualRecGroups: Set<string>[] = [];
  private trampolinedFns: Set<string> = new Set();

  generate(program: AST.Program): string {
    this.output = [];
    this.testNames = [];

    // Header
    this.emit("// Generated by PLang compiler");
    this.emit(`// Module: ${program.module.path.join(".")}`);
    this.emit('"use strict";');
    this.emit("");

    // Runtime helpers
    this.emitRuntime();

    // Imports (mapped to requires)
    for (const imp of program.imports) {
      this.emitImport(imp);
    }

    if (program.imports.length > 0) this.emit("");

    // Analyze mutual tail recursion groups
    this.analyzeMutualRecursion(program.declarations);

    // Declarations
    for (const decl of program.declarations) {
      this.emitDecl(decl);
      this.emit("");
    }

    // Auto-run main if it exists
    const hasMain = program.declarations.some(
      d => d.kind === "FnDecl" && d.name === "main"
    );
    if (hasMain) {
      this.emit("// Entry point");
      this.emit("if (require.main === module) {");
      this.indent++;
      this.emit("const __result = main();");
      this.emit("if (__result instanceof Promise) __result.catch(e => { console.error(e); process.exit(1); });");
      this.indent--;
      this.emit("}");
    }

    return this.output.join("\n");
  }

  generateTestRunner(program: AST.Program): string {
    const code = this.generate(program);

    if (this.testNames.length === 0) return code;

    const runner: string[] = [code, "", "// Test runner"];
    runner.push("(async () => {");
    runner.push("  let __passed = 0, __failed = 0;");
    for (const name of this.testNames) {
      const fnName = this.testFnName(name);
      runner.push(`  try { await ${fnName}(); __passed++; console.log("  PASS: ${this.escapeStr(name)}"); }`);
      runner.push(`  catch (e) { __failed++; console.error("  FAIL: ${this.escapeStr(name)}", e.message); }`);
    }
    runner.push('  console.log(`\\n${__passed} passed, ${__failed} failed`);');
    runner.push("  if (__failed > 0) process.exit(1);");
    runner.push("})();");

    return runner.join("\n");
  }

  private emitRuntime(): void {
    this.emit("// PLang runtime");
    this.emit("class __PLangError extends Error {");
    this.emit("  constructor(tag, data) { super(tag); this.tag = tag; this.data = data; }");
    this.emit("}");
    this.emit("");
    this.emit("function __ok(value) { return { __tag: 'Ok', value }; }");
    this.emit("function __err(error) { return { __tag: 'Err', error }; }");
    this.emit("function __some(value) { return { __tag: 'Some', value }; }");
    this.emit("const __none = { __tag: 'None' };");
    this.emit("function __wrapOption(val) { return (val == null) ? __none : __some(val); }");
    this.emit("const Some = __some;");
    this.emit("const None = __none;");
    this.emit("");
    this.emit("function __propagate(result) {");
    this.emit("  if (result && result.__tag === 'Err') throw new __PLangError('propagate', result.error);");
    this.emit("  if (result && result.__tag === 'Ok') return result.value;");
    this.emit("  return result;");
    this.emit("}");
    this.emit("");
    this.emit("function __range(start, end) {");
    this.emit("  const arr = [];");
    this.emit("  for (let i = start; i < end; i++) arr.push(i);");
    this.emit("  return arr;");
    this.emit("}");
    this.emit("");
    this.emit("function __approxEq(a, b) { return Math.abs(a - b) < 1e-9; }");
    this.emit("");
    this.emit("function __assert(condition, message) {");
    this.emit('  if (!condition) throw new Error("Assertion failed: " + (message || ""));');
    this.emit("}");
    this.emit("");
    this.emit("function __require(condition) {");
    this.emit('  if (!condition) throw new Error("Precondition failed");');
    this.emit("}");
    this.emit("");
    // String concat
    this.emit("function __concat(a, b) { return String(a) + String(b); }");
    this.emit("");
    // Structured concurrency with cancellation
    this.emit("class __TaskGroup {");
    this.emit("  constructor() { this._tasks = []; this._controller = new AbortController(); }");
    this.emit("  spawn(fn) {");
    this.emit("    const signal = this._controller.signal;");
    this.emit("    this._tasks.push(fn(signal));");
    this.emit("  }");
    this.emit("  async run() {");
    this.emit("    try {");
    this.emit("      return await Promise.all(this._tasks);");
    this.emit("    } catch (e) {");
    this.emit("      this._controller.abort(e);");
    this.emit("      await Promise.allSettled(this._tasks);");
    this.emit("      throw e;");
    this.emit("    }");
    this.emit("  }");
    this.emit("}");
    this.emit("");
    // Channel implementation
    this.emit("class __Channel {");
    this.emit("  constructor(capacity = 0) {");
    this.emit("    this._capacity = capacity;");
    this.emit("    this._buffer = [];");
    this.emit("    this._waitingSenders = [];");
    this.emit("    this._waitingReceivers = [];");
    this.emit("    this._closed = false;");
    this.emit("  }");
    this.emit("  async send(value) {");
    this.emit("    if (this._closed) throw new Error('send on closed channel');");
    this.emit("    if (this._waitingReceivers.length > 0) {");
    this.emit("      const resolve = this._waitingReceivers.shift();");
    this.emit("      resolve(__some(value));");
    this.emit("      return;");
    this.emit("    }");
    this.emit("    if (this._buffer.length < this._capacity) {");
    this.emit("      this._buffer.push(value);");
    this.emit("      return;");
    this.emit("    }");
    this.emit("    return new Promise(resolve => {");
    this.emit("      this._waitingSenders.push({ value, resolve });");
    this.emit("    });");
    this.emit("  }");
    this.emit("  async recv() {");
    this.emit("    if (this._buffer.length > 0) {");
    this.emit("      const value = this._buffer.shift();");
    this.emit("      if (this._waitingSenders.length > 0) {");
    this.emit("        const sender = this._waitingSenders.shift();");
    this.emit("        this._buffer.push(sender.value);");
    this.emit("        sender.resolve();");
    this.emit("      }");
    this.emit("      return __some(value);");
    this.emit("    }");
    this.emit("    if (this._waitingSenders.length > 0) {");
    this.emit("      const sender = this._waitingSenders.shift();");
    this.emit("      sender.resolve();");
    this.emit("      return __some(sender.value);");
    this.emit("    }");
    this.emit("    if (this._closed) return __none;");
    this.emit("    return new Promise(resolve => {");
    this.emit("      this._waitingReceivers.push(resolve);");
    this.emit("    });");
    this.emit("  }");
    this.emit("  close() {");
    this.emit("    this._closed = true;");
    this.emit("    for (const resolve of this._waitingReceivers) resolve(__none);");
    this.emit("    this._waitingReceivers = [];");
    this.emit("  }");
    this.emit("}");
    this.emit("");
    // Select implementation
    this.emit("async function __select(arms) {");
    this.emit("  return new Promise((resolve, reject) => {");
    this.emit("    let settled = false;");
    this.emit("    const cleanups = [];");
    this.emit("    for (const arm of arms) {");
    this.emit("      if (settled) break;");
    this.emit("      if (arm.type === 'recv') {");
    this.emit("        const r = arm.channel.tryRecv();");
    this.emit("        if (r && r.__tag === 'Some') {");
    this.emit("          settled = true; resolve(arm.handler(r.value)); return;");
    this.emit("        }");
    this.emit("        arm.channel._waitingReceivers.push((val) => {");
    this.emit("          if (!settled) {");
    this.emit("            settled = true;");
    this.emit("            for (const c of cleanups) c();");
    this.emit("            resolve(arm.handler(val && val.__tag === 'Some' ? val.value : undefined));");
    this.emit("          }");
    this.emit("        });");
    this.emit("      } else if (arm.type === 'timeout') {");
    this.emit("        const t = setTimeout(() => {");
    this.emit("          if (!settled) { settled = true; for (const c of cleanups) c(); resolve(arm.handler()); }");
    this.emit("        }, arm.duration);");
    this.emit("        cleanups.push(() => clearTimeout(t));");
    this.emit("      } else if (arm.type === 'send') {");
    this.emit("        const ok = arm.channel.trySend(arm.value);");
    this.emit("        if (ok) { settled = true; resolve(arm.handler()); return; }");
    this.emit("      }");
    this.emit("    }");
    this.emit("  });");
    this.emit("}");
    this.emit("");
    // tryRecv/trySend helpers on Channel
    this.emit("__Channel.prototype.tryRecv = function() {");
    this.emit("  if (this._buffer.length > 0) return __some(this._buffer.shift());");
    this.emit("  if (this._waitingSenders.length > 0) {");
    this.emit("    const s = this._waitingSenders.shift(); s.resolve(); return __some(s.value);");
    this.emit("  }");
    this.emit("  return __none;");
    this.emit("};");
    this.emit("__Channel.prototype.trySend = function(value) {");
    this.emit("  if (this._closed) return false;");
    this.emit("  if (this._waitingReceivers.length > 0) {");
    this.emit("    this._waitingReceivers.shift()(__some(value)); return true;");
    this.emit("  }");
    this.emit("  if (this._buffer.length < this._capacity) { this._buffer.push(value); return true; }");
    this.emit("  return false;");
    this.emit("};");
    this.emit("");
    // Trampoline for mutual tail recursion
    this.emit("function __trampoline(fn) {");
    this.emit("  let result = fn();");
    this.emit("  while (result && result.__tco_continue) {");
    this.emit("    result = result.__tco_fn(...result.__tco_args);");
    this.emit("  }");
    this.emit("  return result;");
    this.emit("}");
    this.emit("function __tco_call(fn, ...args) {");
    this.emit("  return { __tco_continue: true, __tco_fn: fn, __tco_args: args };");
    this.emit("}");
    this.emit("");
    // Standard library stubs
    this.emit("const std = {");
    this.emit("  io: {");
    this.emit("    println: (s) => { console.log(s); return __ok(undefined); },");
    this.emit("    readln: () => __ok(''),");
    this.emit("  },");
    this.emit("  math: {");
    this.emit("    pi: Math.PI,");
    this.emit("    sqrt: Math.sqrt,");
    this.emit("    abs: Math.abs,");
    this.emit("    floor: Math.floor,");
    this.emit("    ceil: Math.ceil,");
    this.emit("    round: Math.round,");
    this.emit("  },");
    this.emit("};");
    this.emit("");
    // Global convenience
    this.emit("const println = std.io.println;");
    this.emit("const math = std.math;");
    this.emit("const to_option = __wrapOption;");
    this.emit("");
  }

  private emitImport(imp: AST.ImportDecl): void {
    // Imports are handled by the runtime stubs for now
    this.emit(`// import: ${imp.path.join(".")}`);
  }

  private emitDecl(decl: AST.TopLevelDecl): void {
    switch (decl.kind) {
      case "FnDecl": this.emitFnDecl(decl); break;
      case "TypeDecl": this.emitTypeDecl(decl); break;
      case "TraitDecl": this.emitTraitDecl(decl); break;
      case "ImplDecl": this.emitImplDecl(decl); break;
      case "LetDecl": this.emitLetDecl(decl); break;
      case "TestDecl": this.emitTestDecl(decl); break;
      case "ExternFnDecl": this.emitExternFnDecl(decl); break;
      case "ExternModuleDecl": this.emitExternModuleDecl(decl); break;
    }
  }

  private emitFnDecl(decl: AST.FnDecl): void {
    const asyncPrefix = decl.isAsync ? "async " : "";
    const params = decl.params.map(p => p.name).join(", ");
    const paramNames = decl.params.map(p => p.name);

    if (this.isSelfTailRecursive(decl.name, decl.body)) {
      // Self-recursive: loop transformation
      this.emit(`${asyncPrefix}function ${decl.name}(${params}) {`);
      this.indent++;
      this.emit("while (true) {");
      this.indent++;
      this.emitTcoBlockBody(decl.name, paramNames, decl.body);
      this.indent--;
      this.emit("}");
      this.indent--;
      this.emit("}");
    } else if (this.trampolinedFns.has(decl.name)) {
      // Mutual recursion: trampoline transformation
      this.emit(`${asyncPrefix}function ${decl.name}(${params}) {`);
      this.indent++;
      this.emitTrampolinedFnBody(decl.name, decl.body);
      this.indent--;
      this.emit("}");
    } else {
      this.emit(`${asyncPrefix}function ${decl.name}(${params}) {`);
      this.indent++;
      this.emitBlockBody(decl.body);
      this.indent--;
      this.emit("}");
    }

    if (decl.isPublic) {
      this.emit(`module.exports.${decl.name} = ${decl.name};`);
    }
  }

  private emitTypeDecl(decl: AST.TypeDecl): void {
    switch (decl.body.kind) {
      case "RecordTypeBody": {
        // Generate a factory function
        const fields = decl.body.fields.map(f => f.name);
        this.emit(`function ${decl.name}({${fields.join(", ")}}) {`);
        this.emit(`  return { __type: "${decl.name}", ${fields.join(", ")} };`);
        this.emit("}");
        break;
      }
      case "SumTypeBody": {
        // Generate factory functions for each variant
        for (const variant of decl.body.variants) {
          const fields = variant.fields.map(f => f.name);
          if (fields.length > 0) {
            this.emit(`function ${variant.name}({${fields.join(", ")}}) {`);
            this.emit(`  return { __tag: "${variant.name}", __type: "${decl.name}", ${fields.join(", ")} };`);
            this.emit("}");
          } else {
            this.emit(`const ${variant.name} = { __tag: "${variant.name}", __type: "${decl.name}" };`);
          }
        }
        break;
      }
      case "AliasTypeBody":
        this.emit(`// type alias: ${decl.name}`);
        break;
    }
  }

  private emitTraitDecl(decl: AST.TraitDecl): void {
    this.emit(`// trait: ${decl.name}`);
  }

  private emitImplDecl(decl: AST.ImplDecl): void {
    this.emit(`// impl ${decl.traitPath.join(".")} for ${this.typeExprToString(decl.targetType)}`);
    for (const method of decl.methods) {
      const params = method.params
        .filter(p => p.name !== "self")
        .map(p => p.name)
        .join(", ");
      const hasSelf = method.params.some(p => p.name === "self");

      if (hasSelf) {
        // Instance method — add to prototype or as standalone
        this.emit(`function ${decl.traitPath.join("_")}_${method.name}(__self${params ? ", " + params : ""}) {`);
      } else {
        this.emit(`function ${decl.traitPath.join("_")}_${method.name}(${params}) {`);
      }
      this.indent++;
      this.emitBlockBody(method.body);
      this.indent--;
      this.emit("}");
    }
  }

  private emitLetDecl(decl: AST.LetDecl): void {
    this.emit(`const ${decl.name} = ${this.exprToJs(decl.value)};`);
  }

  private emitTestDecl(decl: AST.TestDecl): void {
    const fnName = this.testFnName(decl.name);
    this.testNames.push(decl.name);
    this.emit(`async function ${fnName}() {`);
    this.indent++;
    this.emitBlockBody(decl.body);
    this.indent--;
    this.emit("}");
  }

  private isOptionReturn(returnType?: AST.TypeExpr): boolean {
    return !!returnType && returnType.kind === "NamedType" && returnType.name === "Option";
  }

  private emitExternFnDecl(decl: AST.ExternFnDecl): void {
    const params = decl.params.map(p => p.name).join(", ");
    const asyncPrefix = decl.isAsync ? "async " : "";
    const call = `${decl.jsBinding}(${params})`;
    const body = this.isOptionReturn(decl.returnType) ? `__wrapOption(${call})` : call;
    this.emit(`const ${decl.name} = ${asyncPrefix}(${params}) => ${body};`);
    if (decl.isPublic) {
      this.emit(`module.exports.${decl.name} = ${decl.name};`);
    }
  }

  private emitExternModuleDecl(decl: AST.ExternModuleDecl): void {
    this.emit(`const ${decl.name} = (() => {`);
    this.indent++;
    this.emit(`const __mod = require("${decl.jsModule}");`);
    this.emit(`return {`);
    this.indent++;
    for (const method of decl.methods) {
      const params = method.params.map(p => p.name).join(", ");
      const asyncPrefix = method.isAsync ? "async " : "";
      // "default" means the module export itself is the function (e.g., better-sqlite3)
      let jsFn: string;
      if (method.jsBinding === "default") {
        jsFn = `__mod`;
      } else if (method.jsBinding !== method.name) {
        jsFn = `__mod.${method.jsBinding}`;
      } else {
        jsFn = `__mod.${method.name}`;
      }
      const call = `${jsFn}(${params})`;
      const body = this.isOptionReturn(method.returnType) ? `__wrapOption(${call})` : call;
      this.emit(`${method.name}: ${asyncPrefix}(${params}) => ${body},`);
    }
    this.indent--;
    this.emit(`};`);
    this.indent--;
    this.emit(`})();`);
    if (decl.isPublic) {
      this.emit(`module.exports.${decl.name} = ${decl.name};`);
    }
  }

  // === Expression → JS ===

  private exprToJs(expr: AST.Expr): string {
    switch (expr.kind) {
      case "IntLiteral": return String(expr.value);
      case "FloatLiteral": return String(expr.value);
      case "StrLiteral": return JSON.stringify(expr.value);
      case "CharLiteral": return JSON.stringify(expr.value);
      case "BoolLiteral": return String(expr.value);
      case "NullLiteral": return "null";
      case "Identifier": return expr.name;

      case "BinaryExpr": {
        const left = this.exprToJs(expr.left);
        const right = this.exprToJs(expr.right);
        if (expr.operator === "++") return `__concat(${left}, ${right})`;
        if (expr.operator === "~=") return `__approxEq(${left}, ${right})`;
        return `(${left} ${expr.operator} ${right})`;
      }

      case "UnaryExpr":
        return `${expr.operator}${this.exprToJs(expr.operand)}`;

      case "CallExpr": {
        const callee = this.exprToJs(expr.callee);
        const args = expr.args.map(a => this.exprToJs(a)).join(", ");
        // Wrap calls to trampolined functions from outside their group
        if (expr.callee.kind === "Identifier" && this.trampolinedFns.has(expr.callee.name)) {
          return `__trampoline(() => ${callee}(${args}))`;
        }
        return `${callee}(${args})`;
      }

      case "MemberExpr":
        return `${this.exprToJs(expr.object)}.${expr.member}`;

      case "PropagateExpr":
        return `__propagate(${this.exprToJs(expr.expr)})`;

      case "IfExpr": {
        const cond = this.exprToJs(expr.condition);
        const then = this.blockToJsExpr(expr.then);
        if (expr.else_) {
          const els = expr.else_.kind === "IfExpr"
            ? this.exprToJs(expr.else_)
            : this.blockToJsExpr(expr.else_);
          return `(${cond} ? ${then} : ${els})`;
        }
        return `(${cond} ? ${then} : undefined)`;
      }

      case "MatchExpr":
        return this.matchToJs(expr);

      case "ForExpr": {
        const iterable = this.exprToJs(expr.iterable);
        return `${iterable}.map((${expr.variable}) => ${this.blockToJsExpr(expr.body)})`;
      }

      case "WhileExpr":
        // While as expression returns void — wrap in IIFE
        return `(() => { while (${this.exprToJs(expr.condition)}) ${this.blockToJsInline(expr.body)} })()`;

      case "BlockExpr":
        return this.blockToJsExpr(expr);

      case "LambdaExpr": {
        const params = expr.params.map(p => p.name).join(", ");
        return `(${params}) => ${this.blockToJsExpr(expr.body)}`;
      }

      case "ListExpr":
        return `[${expr.elements.map(e => this.exprToJs(e)).join(", ")}]`;

      case "ObjectLiteral": {
        if (expr.fields.length === 0) return "{}";
        const fields = expr.fields.map(f => `${f.name}: ${this.exprToJs(f.value)}`);
        return `({ ${fields.join(", ")} })`;
      }

      case "RecordExpr": {
        const fields = expr.fields.map(f => {
          if (f.value.kind === "Identifier" && f.value.name === f.name) {
            return f.name; // shorthand
          }
          return `${f.name}: ${this.exprToJs(f.value)}`;
        });
        return `${expr.typeName}({${fields.join(", ")}})`;
      }

      case "RecordUpdateExpr": {
        const base = this.exprToJs(expr.base);
        const updates = expr.updates.map(f => `${f.name}: ${this.exprToJs(f.value)}`).join(", ");
        return `{...${base}, ${updates}}`;
      }

      case "PipeExpr": {
        const callee = this.exprToJs(expr.right.callee);
        const args = [this.exprToJs(expr.left), ...expr.right.args.map(a => this.exprToJs(a))].join(", ");
        return `${callee}(${args})`;
      }

      case "ReturnExpr":
        return expr.value ? `return ${this.exprToJs(expr.value)}` : "return";

      case "BreakExpr": return "break";
      case "ContinueExpr": return "continue";

      case "AwaitExpr":
        return `await ${this.exprToJs(expr.expr)}`;

      case "TaskGroupExpr":
        return `await (async () => { const ${expr.paramName} = new __TaskGroup(); ${this.blockToJsInline(expr.body)}; return ${expr.paramName}.run(); })()`;

      case "ChannelExpr":
        return expr.capacity
          ? `new __Channel(${this.exprToJs(expr.capacity)})`
          : `new __Channel()`;

      case "SendExpr":
        return `await ${this.exprToJs(expr.channel)}.send(${this.exprToJs(expr.value)})`;

      case "RecvExpr":
        return `await ${this.exprToJs(expr.channel)}.recv()`;

      case "SelectExpr":
        return this.selectToJs(expr);

      case "TimeoutExpr":
        return `new Promise(r => setTimeout(r, ${this.exprToJs(expr.duration)}))`;

      case "AssertExpr":
        return `__assert(${this.exprToJs(expr.condition)}, ${JSON.stringify(this.exprToSourceString(expr.condition))})`;

      case "RangeExpr":
        return `__range(${this.exprToJs(expr.start)}, ${this.exprToJs(expr.end)})`;

      default:
        return `/* unsupported: ${(expr as any).kind} */`;
    }
  }

  private selectToJs(expr: AST.SelectExpr): string {
    const arms = expr.arms.map(arm => {
      const body = this.exprToJs(arm.body);
      switch (arm.operation.kind) {
        case "RecvExpr": {
          const ch = this.exprToJs(arm.operation.channel);
          const paramName = arm.bindName || "__val";
          return `{ type: 'recv', channel: ${ch}, handler: (${paramName}) => ${body} }`;
        }
        case "SendExpr": {
          const ch = this.exprToJs(arm.operation.channel);
          const val = this.exprToJs(arm.operation.value);
          return `{ type: 'send', channel: ${ch}, value: ${val}, handler: () => ${body} }`;
        }
        case "TimeoutExpr": {
          const dur = this.exprToJs(arm.operation.duration);
          return `{ type: 'timeout', duration: ${dur}, handler: () => ${body} }`;
        }
      }
    });
    return `await __select([${arms.join(", ")}])`;
  }

  private matchToJs(expr: AST.MatchExpr): string {
    const subject = this.exprToJs(expr.subject);
    const tempVar = `__match_${Math.floor(Math.random() * 10000)}`;

    const arms = expr.arms.map(arm => {
      const { condition, bindings } = this.patternToCondition(arm.pattern, tempVar);
      const body = this.exprToJs(arm.body);
      const bindingCode = bindings.length > 0
        ? bindings.map(b => `const ${b.name} = ${b.expr};`).join(" ") + " "
        : "";
      return `${condition} ? (() => { ${bindingCode}return ${body}; })()`;
    });

    return `((${tempVar}) => ${arms.join(" : ")} : undefined)(${subject})`;
  }

  private patternToCondition(
    pattern: AST.Pattern,
    subject: string,
  ): { condition: string; bindings: { name: string; expr: string }[] } {
    switch (pattern.kind) {
      case "WildcardPattern":
        return { condition: "true", bindings: [] };

      case "IdentifierPattern":
        return { condition: "true", bindings: [{ name: pattern.name, expr: subject }] };

      case "LiteralPattern": {
        const value = this.exprToJs(pattern.value);
        return { condition: `${subject} === ${value}`, bindings: [] };
      }

      case "VariantPattern": {
        const bindings: { name: string; expr: string }[] = [];
        for (const field of pattern.fields) {
          if (!field.isRest) {
            bindings.push({ name: field.name, expr: `${subject}.${field.name}` });
          }
        }
        return {
          condition: `${subject}.__tag === "${pattern.name}"`,
          bindings,
        };
      }

      case "ListPattern": {
        const conditions: string[] = [];
        const bindings: { name: string; expr: string }[] = [];
        if (!pattern.hasRest) {
          conditions.push(`${subject}.length === ${pattern.elements.length}`);
        } else {
          conditions.push(`${subject}.length >= ${pattern.elements.length}`);
        }
        for (let i = 0; i < pattern.elements.length; i++) {
          const sub = this.patternToCondition(pattern.elements[i], `${subject}[${i}]`);
          if (sub.condition !== "true") conditions.push(sub.condition);
          bindings.push(...sub.bindings);
        }
        return { condition: conditions.join(" && ") || "true", bindings };
      }
    }
  }

  // === Block emission ===

  private emitBlockBody(block: AST.BlockExpr): void {
    for (const stmt of block.statements) {
      this.emitStatement(stmt);
    }
    if (block.finalExpr) {
      this.emit(`return ${this.exprToJs(block.finalExpr)};`);
    }
  }

  private emitStatement(stmt: AST.Statement): void {
    switch (stmt.kind) {
      case "LetDecl":
        this.emit(`const ${stmt.name} = ${this.exprToJs(stmt.value)};`);
        break;
      case "VarDecl":
        this.emit(`let ${stmt.name} = ${this.exprToJs(stmt.value)};`);
        break;
      case "AssignStmt":
        this.emit(`${stmt.target} ${stmt.operator} ${this.exprToJs(stmt.value)};`);
        break;
      case "ExprStmt":
        this.emit(`${this.exprToJs(stmt.expr)};`);
        break;
      case "RequireStmt":
        this.emit(`__require(${this.exprToJs(stmt.condition)});`);
        break;
      case "EnsureStmt":
        // Postconditions are checked after the function body — emitted as a wrapper
        this.emit(`// ensure: |${stmt.paramName}| ${this.exprToSourceString(stmt.condition)}`);
        break;
    }
  }

  private blockToJsExpr(block: AST.BlockExpr): string {
    if (block.statements.length === 0 && block.finalExpr) {
      return this.exprToJs(block.finalExpr);
    }

    const parts: string[] = [];
    for (const stmt of block.statements) {
      parts.push(this.stmtToJs(stmt));
    }
    if (block.finalExpr) {
      parts.push(`return ${this.exprToJs(block.finalExpr)};`);
    }
    return `(() => { ${parts.join(" ")} })()`;
  }

  private blockToJsInline(block: AST.BlockExpr): string {
    const parts: string[] = [];
    for (const stmt of block.statements) {
      parts.push(this.stmtToJs(stmt));
    }
    if (block.finalExpr) {
      parts.push(this.exprToJs(block.finalExpr) + ";");
    }
    return `{ ${parts.join(" ")} }`;
  }

  private stmtToJs(stmt: AST.Statement): string {
    switch (stmt.kind) {
      case "LetDecl": return `const ${stmt.name} = ${this.exprToJs(stmt.value)};`;
      case "VarDecl": return `let ${stmt.name} = ${this.exprToJs(stmt.value)};`;
      case "AssignStmt": return `${stmt.target} ${stmt.operator} ${this.exprToJs(stmt.value)};`;
      case "ExprStmt": return `${this.exprToJs(stmt.expr)};`;
      case "RequireStmt": return `__require(${this.exprToJs(stmt.condition)});`;
      case "EnsureStmt": return `/* ensure */`;
    }
  }

  // === Tail Call Optimization ===

  // Check if an expression is a self-call in tail position
  private isInTailPosition(fnName: string, expr: AST.Expr): boolean {
    switch (expr.kind) {
      case "CallExpr":
        return expr.callee.kind === "Identifier" && expr.callee.name === fnName;
      case "IfExpr": {
        const thenTail = expr.then.finalExpr
          ? this.isInTailPosition(fnName, expr.then.finalExpr)
          : false;
        const elseTail = expr.else_
          ? (expr.else_.kind === "IfExpr"
            ? this.isInTailPosition(fnName, expr.else_)
            : (expr.else_.finalExpr ? this.isInTailPosition(fnName, expr.else_.finalExpr) : false))
          : false;
        return thenTail || elseTail;
      }
      case "MatchExpr":
        return expr.arms.some(arm => this.isInTailPosition(fnName, arm.body));
      case "BlockExpr":
        return expr.finalExpr ? this.isInTailPosition(fnName, expr.finalExpr) : false;
      case "ReturnExpr":
        return expr.value ? this.isInTailPosition(fnName, expr.value) : false;
      default:
        return false;
    }
  }

  // Check if body contains any self-call in tail position (also checks statements for return exprs)
  private isSelfTailRecursive(fnName: string, body: AST.BlockExpr): boolean {
    if (body.finalExpr && this.isInTailPosition(fnName, body.finalExpr)) return true;
    for (const stmt of body.statements) {
      if (stmt.kind === "ExprStmt" && stmt.expr.kind === "ReturnExpr" &&
          stmt.expr.value && this.isInTailPosition(fnName, stmt.expr.value)) {
        return true;
      }
    }
    return false;
  }

  // Find tail calls to other functions (for mutual recursion detection)
  private findTailCallTargets(expr: AST.Expr, targets: Set<string>): void {
    switch (expr.kind) {
      case "CallExpr":
        if (expr.callee.kind === "Identifier") targets.add(expr.callee.name);
        break;
      case "IfExpr":
        if (expr.then.finalExpr) this.findTailCallTargets(expr.then.finalExpr, targets);
        if (expr.else_) {
          if (expr.else_.kind === "IfExpr") this.findTailCallTargets(expr.else_, targets);
          else if (expr.else_.finalExpr) this.findTailCallTargets(expr.else_.finalExpr, targets);
        }
        break;
      case "MatchExpr":
        for (const arm of expr.arms) this.findTailCallTargets(arm.body, targets);
        break;
      case "BlockExpr":
        if (expr.finalExpr) this.findTailCallTargets(expr.finalExpr, targets);
        break;
      case "ReturnExpr":
        if (expr.value) this.findTailCallTargets(expr.value, targets);
        break;
    }
  }

  // Analyze declarations to find mutual recursion groups
  private analyzeMutualRecursion(declarations: AST.TopLevelDecl[]): void {
    this.mutualRecGroups = [];
    this.trampolinedFns = new Set();

    const fnDecls = declarations.filter(d => d.kind === "FnDecl") as AST.FnDecl[];
    const fnNames = new Set(fnDecls.map(d => d.name));

    // Build call graph: fnName -> set of functions it tail-calls (excluding self)
    const tailCallGraph = new Map<string, Set<string>>();
    for (const decl of fnDecls) {
      const targets = new Set<string>();
      if (decl.body.finalExpr) this.findTailCallTargets(decl.body.finalExpr, targets);
      for (const stmt of decl.body.statements) {
        if (stmt.kind === "ExprStmt" && stmt.expr.kind === "ReturnExpr" && stmt.expr.value) {
          this.findTailCallTargets(stmt.expr.value, targets);
        }
      }
      // Remove self (handled by loop transform) and non-declared functions
      targets.delete(decl.name);
      for (const t of targets) {
        if (!fnNames.has(t)) targets.delete(t);
      }
      if (targets.size > 0) tailCallGraph.set(decl.name, targets);
    }

    // Find mutual recursion: if A tail-calls B and B tail-calls A, they form a group
    const visited = new Set<string>();
    for (const [fnName, targets] of tailCallGraph) {
      if (visited.has(fnName)) continue;
      const group = new Set<string>();
      // BFS to find connected component of mutual tail calls
      const queue = [fnName];
      while (queue.length > 0) {
        const current = queue.shift()!;
        if (group.has(current)) continue;
        // Check if current is reachable from any group member
        const currentTargets = tailCallGraph.get(current);
        if (!currentTargets) continue;
        // Only add to group if there's mutual dependency
        let isMutual = current === fnName; // seed
        if (!isMutual) {
          for (const member of group) {
            if (currentTargets.has(member)) { isMutual = true; break; }
          }
        }
        if (!isMutual) continue;
        group.add(current);
        visited.add(current);
        for (const target of currentTargets) {
          if (!group.has(target)) queue.push(target);
        }
      }
      if (group.size >= 2) {
        this.mutualRecGroups.push(group);
        for (const name of group) this.trampolinedFns.add(name);
      }
    }
  }

  // Check if a call target is a trampolined function (for wrapping call sites)
  private isTrampolinedCall(expr: AST.Expr): boolean {
    return expr.kind === "CallExpr" &&
           expr.callee.kind === "Identifier" &&
           this.trampolinedFns.has(expr.callee.name);
  }

  // === Self-recursion loop transform ===

  private emitTcoBlockBody(fnName: string, paramNames: string[], block: AST.BlockExpr): void {
    for (const stmt of block.statements) {
      this.emitTcoStatement(fnName, paramNames, stmt);
    }
    if (block.finalExpr) {
      this.emitTcoExpr(fnName, paramNames, block.finalExpr);
    }
  }

  private emitTcoStatement(fnName: string, paramNames: string[], stmt: AST.Statement): void {
    if (stmt.kind === "ExprStmt" && stmt.expr.kind === "ReturnExpr" &&
        stmt.expr.value && stmt.expr.value.kind === "CallExpr" &&
        stmt.expr.value.callee.kind === "Identifier" &&
        stmt.expr.value.callee.name === fnName) {
      this.emitTailCallContinue(paramNames, stmt.expr.value.args);
      return;
    }
    this.emitStatement(stmt);
  }

  private emitTcoExpr(fnName: string, paramNames: string[], expr: AST.Expr): void {
    // Self-call in tail position -> reassign params + continue
    if (expr.kind === "CallExpr" && expr.callee.kind === "Identifier" && expr.callee.name === fnName) {
      this.emitTailCallContinue(paramNames, expr.args);
      return;
    }

    // Return with self-call
    if (expr.kind === "ReturnExpr" && expr.value &&
        expr.value.kind === "CallExpr" && expr.value.callee.kind === "Identifier" &&
        expr.value.callee.name === fnName) {
      this.emitTailCallContinue(paramNames, expr.value.args);
      return;
    }

    // If expression -> statement-form with TCO in branches
    if (expr.kind === "IfExpr") {
      this.emitTcoIf(fnName, paramNames, expr);
      return;
    }

    // Match expression -> statement-form with TCO in arms
    if (expr.kind === "MatchExpr") {
      this.emitTcoMatch(fnName, paramNames, expr);
      return;
    }

    // Nested block
    if (expr.kind === "BlockExpr") {
      this.emitTcoBlockBody(fnName, paramNames, expr);
      return;
    }

    // Not a tail call — emit as normal return
    this.emit(`return ${this.exprToJs(expr)};`);
  }

  private emitTailCallContinue(paramNames: string[], args: AST.Expr[]): void {
    if (args.length === 1) {
      this.emit(`${paramNames[0]} = ${this.exprToJs(args[0])};`);
    } else {
      // Use temp vars to avoid order-of-evaluation issues
      for (let i = 0; i < args.length; i++) {
        this.emit(`let __tco_${paramNames[i]} = ${this.exprToJs(args[i])};`);
      }
      for (let i = 0; i < paramNames.length; i++) {
        this.emit(`${paramNames[i]} = __tco_${paramNames[i]};`);
      }
    }
    this.emit("continue;");
  }

  private emitTcoIf(fnName: string, paramNames: string[], expr: AST.IfExpr): void {
    this.emit(`if (${this.exprToJs(expr.condition)}) {`);
    this.indent++;
    this.emitTcoBlockBody(fnName, paramNames, expr.then);
    this.indent--;
    if (expr.else_) {
      if (expr.else_.kind === "IfExpr") {
        this.emit("} else {");
        this.indent++;
        this.emitTcoIf(fnName, paramNames, expr.else_);
        this.indent--;
      } else {
        this.emit("} else {");
        this.indent++;
        this.emitTcoBlockBody(fnName, paramNames, expr.else_);
        this.indent--;
      }
    }
    this.emit("}");
  }

  private emitTcoMatch(fnName: string, paramNames: string[], expr: AST.MatchExpr): void {
    const subject = this.exprToJs(expr.subject);
    const tempVar = `__match_${Math.floor(Math.random() * 10000)}`;
    this.emit(`const ${tempVar} = ${subject};`);

    for (let i = 0; i < expr.arms.length; i++) {
      const arm = expr.arms[i];
      const { condition, bindings } = this.patternToCondition(arm.pattern, tempVar);
      const prefix = i === 0 ? "if" : "} else if";
      this.emit(`${prefix} (${condition}) {`);
      this.indent++;
      for (const b of bindings) {
        this.emit(`const ${b.name} = ${b.expr};`);
      }
      this.emitTcoExpr(fnName, paramNames, arm.body);
      this.indent--;
    }
    this.emit("}");
  }

  // === Mutual recursion trampoline transform ===

  private emitTrampolinedFnBody(fnName: string, body: AST.BlockExpr): void {
    for (const stmt of body.statements) {
      this.emitTrampolineStatement(fnName, stmt);
    }
    if (body.finalExpr) {
      this.emitTrampolineExpr(fnName, body.finalExpr);
    }
  }

  private emitTrampolineStatement(fnName: string, stmt: AST.Statement): void {
    if (stmt.kind === "ExprStmt" && stmt.expr.kind === "ReturnExpr" && stmt.expr.value) {
      if (this.isMutualTailCall(fnName, stmt.expr.value)) {
        this.emitTrampolineReturn(stmt.expr.value as AST.CallExpr);
        return;
      }
    }
    this.emitStatement(stmt);
  }

  private emitTrampolineExpr(fnName: string, expr: AST.Expr): void {
    if (this.isMutualTailCall(fnName, expr)) {
      this.emitTrampolineReturn(expr as AST.CallExpr);
      return;
    }
    if (expr.kind === "ReturnExpr" && expr.value && this.isMutualTailCall(fnName, expr.value)) {
      this.emitTrampolineReturn(expr.value as AST.CallExpr);
      return;
    }
    if (expr.kind === "IfExpr") {
      this.emitTrampolineIf(fnName, expr);
      return;
    }
    if (expr.kind === "MatchExpr") {
      this.emitTrampolineMatch(fnName, expr);
      return;
    }
    if (expr.kind === "BlockExpr") {
      this.emitTrampolinedFnBody(fnName, expr);
      return;
    }
    this.emit(`return ${this.exprToJs(expr)};`);
  }

  private isMutualTailCall(fnName: string, expr: AST.Expr): boolean {
    return expr.kind === "CallExpr" &&
           expr.callee.kind === "Identifier" &&
           expr.callee.name !== fnName &&
           this.trampolinedFns.has(expr.callee.name);
  }

  private emitTrampolineReturn(call: AST.CallExpr): void {
    const callee = this.exprToJs(call.callee);
    const args = call.args.map(a => this.exprToJs(a)).join(", ");
    this.emit(`return __tco_call(${callee}, ${args});`);
  }

  private emitTrampolineIf(fnName: string, expr: AST.IfExpr): void {
    this.emit(`if (${this.exprToJs(expr.condition)}) {`);
    this.indent++;
    this.emitTrampolinedFnBody(fnName, expr.then);
    this.indent--;
    if (expr.else_) {
      if (expr.else_.kind === "IfExpr") {
        this.emit("} else {");
        this.indent++;
        this.emitTrampolineIf(fnName, expr.else_);
        this.indent--;
      } else {
        this.emit("} else {");
        this.indent++;
        this.emitTrampolinedFnBody(fnName, expr.else_);
        this.indent--;
      }
    }
    this.emit("}");
  }

  private emitTrampolineMatch(fnName: string, expr: AST.MatchExpr): void {
    const subject = this.exprToJs(expr.subject);
    const tempVar = `__match_${Math.floor(Math.random() * 10000)}`;
    this.emit(`const ${tempVar} = ${subject};`);

    for (let i = 0; i < expr.arms.length; i++) {
      const arm = expr.arms[i];
      const { condition, bindings } = this.patternToCondition(arm.pattern, tempVar);
      const prefix = i === 0 ? "if" : "} else if";
      this.emit(`${prefix} (${condition}) {`);
      this.indent++;
      for (const b of bindings) {
        this.emit(`const ${b.name} = ${b.expr};`);
      }
      this.emitTrampolineExpr(fnName, arm.body);
      this.indent--;
    }
    this.emit("}");
  }

  // === Helpers ===

  private emit(line: string): void {
    const indentation = "  ".repeat(this.indent);
    this.output.push(indentation + line);
  }

  private testFnName(name: string): string {
    return "__test_" + name.replace(/[^a-zA-Z0-9]/g, "_");
  }

  private typeExprToString(type: AST.TypeExpr): string {
    switch (type.kind) {
      case "NamedType": return type.name + (type.typeArgs.length > 0 ? `<${type.typeArgs.map(t => this.typeExprToString(t)).join(", ")}>` : "");
      case "FunctionType": return `(${type.params.map(p => this.typeExprToString(p)).join(", ")}) -> ${this.typeExprToString(type.returnType)}`;
      case "TupleType": return `(${type.elements.map(e => this.typeExprToString(e)).join(", ")})`;
      case "RecordType": return `{ ${type.fields.map(f => `${f.name}: ${this.typeExprToString(f.type)}`).join(", ")} }`;
    }
  }

  private exprToSourceString(expr: AST.Expr): string {
    // Approximate source reconstruction for error messages
    switch (expr.kind) {
      case "BinaryExpr": return `${this.exprToSourceString(expr.left)} ${expr.operator} ${this.exprToSourceString(expr.right)}`;
      case "Identifier": return expr.name;
      case "IntLiteral": return String(expr.value);
      case "CallExpr": return `${this.exprToSourceString(expr.callee)}(...)`;
      default: return "<expr>";
    }
  }

  private escapeStr(s: string): string {
    return s.replace(/"/g, '\\"');
  }
}
